before_install:
- pip install --user pexpect


script:
- install --directory private
# - openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout private/selfsigned.key -out selfsigned.crt
- python openssl-req-pexpect.py
- openssl dhparam -out dhparam.pem 2048

after_script:
- ls --recursive --color
